### PR TITLE
Fix dev86

### PR DESCRIPTION
**Pull request by pietrushnic**
Does it make sense for sending upstream?

### CODE REVIEW

**Comment by macpijan** [comment]
@pietrushnic Yes

**Comment by pietrushnic** [comment]
@Asiderr can you send that patch on my behalf to the mailing list? If not then please point me to procedure how to do that I assume `git send-email` but are there any additional checks needed?

**Comment by Asiderr** [comment]
@pietrushnic I can do this. I sent you and @macpijan an email with this patch. Please make sure it looks okay, and I will send the change to ml.

**Comment by pietrushnic** [comment]
@Asiderr to me it looks fine

**Comment by Asiderr** [comment]
@pietrushnic I've sent patch to ml

**Comment by Asiderr** [comment]
@pietrushnic The patch is merged

**Comment by pietrushnic** [comment]
@macpijan how we should handle that in Github? We should probably fetch from upstream?

**Comment by macpijan** [comment]
@pietrushnic  Yes, we should close that and fetch from upstream if needed.
In general, we should not use github fork for builds in the long term and use it as a workspace for preparing / reviewing patches.

**Pull request closed without merging**
